use std::str::FromStr;

/// ISO 3166-1 alpha-2 country codes as sent by CloudFront in the
/// `cloudfront-viewer-country` header.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CloudFrontCountry {
    Afghanistan,
    AlandIslands,
    Albania,
    Algeria,
    AmericanSamoa,
    Andorra,
    Angola,
    Anguilla,
    Antarctica,
    AntiguaAndBarbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    Bolivia,
    BonaireSintEustatiusAndSaba,
    BosniaAndHerzegovina,
    Botswana,
    BouvetIsland,
    Brazil,
    BritishIndianOceanTerritory,
    Brunei,
    Bulgaria,
    BurkinaFaso,
    Burundi,
    CaboVerde,
    Cambodia,
    Cameroon,
    Canada,
    CaymanIslands,
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    ChristmasIsland,
    CocosIslands,
    Colombia,
    Comoros,
    Congo,
    CongoDemocraticRepublic,
    CookIslands,
    CostaRica,
    CoteDivoire,
    Croatia,
    Cuba,
    Curacao,
    Cyprus,
    CzechRepublic,
    Denmark,
    Djibouti,
    Dominica,
    DominicanRepublic,
    Ecuador,
    Egypt,
    ElSalvador,
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Eswatini,
    Ethiopia,
    FalklandIslands,
    FaroeIslands,
    Fiji,
    Finland,
    France,
    FrenchGuiana,
    FrenchPolynesia,
    FrenchSouthernTerritories,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guernsey,
    Guinea,
    GuineaBissau,
    Guyana,
    Haiti,
    HeardIslandAndMcdonaldIslands,
    HolySee,
    Honduras,
    HongKong,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    IsleOfMan,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jersey,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    NorthKorea,
    SouthKorea,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macao,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    MarshallIslands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    NewCaledonia,
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    NorfolkIsland,
    NorthMacedonia,
    NorthernMarianaIslands,
    Norway,
    Oman,
    Pakistan,
    Palau,
    Palestine,
    Panama,
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Pitcairn,
    Poland,
    Portugal,
    PuertoRico,
    Qatar,
    Reunion,
    Romania,
    Russia,
    Rwanda,
    SaintBarthelemy,
    SaintHelena,
    SaintKittsAndNevis,
    SaintLucia,
    SaintMartin,
    SaintPierreAndMiquelon,
    SaintVincentAndTheGrenadines,
    Samoa,
    SanMarino,
    SaoTomeAndPrincipe,
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    SintMaarten,
    Slovakia,
    Slovenia,
    SolomonIslands,
    Somalia,
    SouthAfrica,
    SouthGeorgiaAndSouthSandwichIslands,
    SouthSudan,
    Spain,
    SriLanka,
    Sudan,
    Suriname,
    SvalbardAndJanMayen,
    Sweden,
    Switzerland,
    Syria,
    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    TimorLeste,
    Togo,
    Tokelau,
    Tonga,
    TrinidadAndTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    TurksAndCaicosIslands,
    Tuvalu,
    Uganda,
    Ukraine,
    UnitedArabEmirates,
    UnitedKingdom,
    UnitedStates,
    UnitedStatesMinorOutlyingIslands,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    Venezuela,
    Vietnam,
    VirginIslandsBritish,
    VirginIslandsUs,
    WallisAndFutuna,
    WesternSahara,
    Yemen,
    Zambia,
    Zimbabwe,
}

impl std::str::FromStr for CloudFrontCountry {
    type Err = UnknownCountryCode;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AF" => Ok(Self::Afghanistan),
            "AX" => Ok(Self::AlandIslands),
            "AL" => Ok(Self::Albania),
            "DZ" => Ok(Self::Algeria),
            "AS" => Ok(Self::AmericanSamoa),
            "AD" => Ok(Self::Andorra),
            "AO" => Ok(Self::Angola),
            "AI" => Ok(Self::Anguilla),
            "AQ" => Ok(Self::Antarctica),
            "AG" => Ok(Self::AntiguaAndBarbuda),
            "AR" => Ok(Self::Argentina),
            "AM" => Ok(Self::Armenia),
            "AW" => Ok(Self::Aruba),
            "AU" => Ok(Self::Australia),
            "AT" => Ok(Self::Austria),
            "AZ" => Ok(Self::Azerbaijan),
            "BS" => Ok(Self::Bahamas),
            "BH" => Ok(Self::Bahrain),
            "BD" => Ok(Self::Bangladesh),
            "BB" => Ok(Self::Barbados),
            "BY" => Ok(Self::Belarus),
            "BE" => Ok(Self::Belgium),
            "BZ" => Ok(Self::Belize),
            "BJ" => Ok(Self::Benin),
            "BM" => Ok(Self::Bermuda),
            "BT" => Ok(Self::Bhutan),
            "BO" => Ok(Self::Bolivia),
            "BQ" => Ok(Self::BonaireSintEustatiusAndSaba),
            "BA" => Ok(Self::BosniaAndHerzegovina),
            "BW" => Ok(Self::Botswana),
            "BV" => Ok(Self::BouvetIsland),
            "BR" => Ok(Self::Brazil),
            "IO" => Ok(Self::BritishIndianOceanTerritory),
            "BN" => Ok(Self::Brunei),
            "BG" => Ok(Self::Bulgaria),
            "BF" => Ok(Self::BurkinaFaso),
            "BI" => Ok(Self::Burundi),
            "CV" => Ok(Self::CaboVerde),
            "KH" => Ok(Self::Cambodia),
            "CM" => Ok(Self::Cameroon),
            "CA" => Ok(Self::Canada),
            "KY" => Ok(Self::CaymanIslands),
            "CF" => Ok(Self::CentralAfricanRepublic),
            "TD" => Ok(Self::Chad),
            "CL" => Ok(Self::Chile),
            "CN" => Ok(Self::China),
            "CX" => Ok(Self::ChristmasIsland),
            "CC" => Ok(Self::CocosIslands),
            "CO" => Ok(Self::Colombia),
            "KM" => Ok(Self::Comoros),
            "CG" => Ok(Self::Congo),
            "CD" => Ok(Self::CongoDemocraticRepublic),
            "CK" => Ok(Self::CookIslands),
            "CR" => Ok(Self::CostaRica),
            "CI" => Ok(Self::CoteDivoire),
            "HR" => Ok(Self::Croatia),
            "CU" => Ok(Self::Cuba),
            "CW" => Ok(Self::Curacao),
            "CY" => Ok(Self::Cyprus),
            "CZ" => Ok(Self::CzechRepublic),
            "DK" => Ok(Self::Denmark),
            "DJ" => Ok(Self::Djibouti),
            "DM" => Ok(Self::Dominica),
            "DO" => Ok(Self::DominicanRepublic),
            "EC" => Ok(Self::Ecuador),
            "EG" => Ok(Self::Egypt),
            "SV" => Ok(Self::ElSalvador),
            "GQ" => Ok(Self::EquatorialGuinea),
            "ER" => Ok(Self::Eritrea),
            "EE" => Ok(Self::Estonia),
            "SZ" => Ok(Self::Eswatini),
            "ET" => Ok(Self::Ethiopia),
            "FK" => Ok(Self::FalklandIslands),
            "FO" => Ok(Self::FaroeIslands),
            "FJ" => Ok(Self::Fiji),
            "FI" => Ok(Self::Finland),
            "FR" => Ok(Self::France),
            "GF" => Ok(Self::FrenchGuiana),
            "PF" => Ok(Self::FrenchPolynesia),
            "TF" => Ok(Self::FrenchSouthernTerritories),
            "GA" => Ok(Self::Gabon),
            "GM" => Ok(Self::Gambia),
            "GE" => Ok(Self::Georgia),
            "DE" => Ok(Self::Germany),
            "GH" => Ok(Self::Ghana),
            "GI" => Ok(Self::Gibraltar),
            "GR" => Ok(Self::Greece),
            "GL" => Ok(Self::Greenland),
            "GD" => Ok(Self::Grenada),
            "GP" => Ok(Self::Guadeloupe),
            "GU" => Ok(Self::Guam),
            "GT" => Ok(Self::Guatemala),
            "GG" => Ok(Self::Guernsey),
            "GN" => Ok(Self::Guinea),
            "GW" => Ok(Self::GuineaBissau),
            "GY" => Ok(Self::Guyana),
            "HT" => Ok(Self::Haiti),
            "HM" => Ok(Self::HeardIslandAndMcdonaldIslands),
            "VA" => Ok(Self::HolySee),
            "HN" => Ok(Self::Honduras),
            "HK" => Ok(Self::HongKong),
            "HU" => Ok(Self::Hungary),
            "IS" => Ok(Self::Iceland),
            "IN" => Ok(Self::India),
            "ID" => Ok(Self::Indonesia),
            "IR" => Ok(Self::Iran),
            "IQ" => Ok(Self::Iraq),
            "IE" => Ok(Self::Ireland),
            "IM" => Ok(Self::IsleOfMan),
            "IL" => Ok(Self::Israel),
            "IT" => Ok(Self::Italy),
            "JM" => Ok(Self::Jamaica),
            "JP" => Ok(Self::Japan),
            "JE" => Ok(Self::Jersey),
            "JO" => Ok(Self::Jordan),
            "KZ" => Ok(Self::Kazakhstan),
            "KE" => Ok(Self::Kenya),
            "KI" => Ok(Self::Kiribati),
            "KP" => Ok(Self::NorthKorea),
            "KR" => Ok(Self::SouthKorea),
            "KW" => Ok(Self::Kuwait),
            "KG" => Ok(Self::Kyrgyzstan),
            "LA" => Ok(Self::Laos),
            "LV" => Ok(Self::Latvia),
            "LB" => Ok(Self::Lebanon),
            "LS" => Ok(Self::Lesotho),
            "LR" => Ok(Self::Liberia),
            "LY" => Ok(Self::Libya),
            "LI" => Ok(Self::Liechtenstein),
            "LT" => Ok(Self::Lithuania),
            "LU" => Ok(Self::Luxembourg),
            "MO" => Ok(Self::Macao),
            "MG" => Ok(Self::Madagascar),
            "MW" => Ok(Self::Malawi),
            "MY" => Ok(Self::Malaysia),
            "MV" => Ok(Self::Maldives),
            "ML" => Ok(Self::Mali),
            "MT" => Ok(Self::Malta),
            "MH" => Ok(Self::MarshallIslands),
            "MQ" => Ok(Self::Martinique),
            "MR" => Ok(Self::Mauritania),
            "MU" => Ok(Self::Mauritius),
            "YT" => Ok(Self::Mayotte),
            "MX" => Ok(Self::Mexico),
            "FM" => Ok(Self::Micronesia),
            "MD" => Ok(Self::Moldova),
            "MC" => Ok(Self::Monaco),
            "MN" => Ok(Self::Mongolia),
            "ME" => Ok(Self::Montenegro),
            "MS" => Ok(Self::Montserrat),
            "MA" => Ok(Self::Morocco),
            "MZ" => Ok(Self::Mozambique),
            "MM" => Ok(Self::Myanmar),
            "NA" => Ok(Self::Namibia),
            "NR" => Ok(Self::Nauru),
            "NP" => Ok(Self::Nepal),
            "NL" => Ok(Self::Netherlands),
            "NC" => Ok(Self::NewCaledonia),
            "NZ" => Ok(Self::NewZealand),
            "NI" => Ok(Self::Nicaragua),
            "NE" => Ok(Self::Niger),
            "NG" => Ok(Self::Nigeria),
            "NU" => Ok(Self::Niue),
            "NF" => Ok(Self::NorfolkIsland),
            "MK" => Ok(Self::NorthMacedonia),
            "MP" => Ok(Self::NorthernMarianaIslands),
            "NO" => Ok(Self::Norway),
            "OM" => Ok(Self::Oman),
            "PK" => Ok(Self::Pakistan),
            "PW" => Ok(Self::Palau),
            "PS" => Ok(Self::Palestine),
            "PA" => Ok(Self::Panama),
            "PG" => Ok(Self::PapuaNewGuinea),
            "PY" => Ok(Self::Paraguay),
            "PE" => Ok(Self::Peru),
            "PH" => Ok(Self::Philippines),
            "PN" => Ok(Self::Pitcairn),
            "PL" => Ok(Self::Poland),
            "PT" => Ok(Self::Portugal),
            "PR" => Ok(Self::PuertoRico),
            "QA" => Ok(Self::Qatar),
            "RE" => Ok(Self::Reunion),
            "RO" => Ok(Self::Romania),
            "RU" => Ok(Self::Russia),
            "RW" => Ok(Self::Rwanda),
            "BL" => Ok(Self::SaintBarthelemy),
            "SH" => Ok(Self::SaintHelena),
            "KN" => Ok(Self::SaintKittsAndNevis),
            "LC" => Ok(Self::SaintLucia),
            "MF" => Ok(Self::SaintMartin),
            "PM" => Ok(Self::SaintPierreAndMiquelon),
            "VC" => Ok(Self::SaintVincentAndTheGrenadines),
            "WS" => Ok(Self::Samoa),
            "SM" => Ok(Self::SanMarino),
            "ST" => Ok(Self::SaoTomeAndPrincipe),
            "SA" => Ok(Self::SaudiArabia),
            "SN" => Ok(Self::Senegal),
            "RS" => Ok(Self::Serbia),
            "SC" => Ok(Self::Seychelles),
            "SL" => Ok(Self::SierraLeone),
            "SG" => Ok(Self::Singapore),
            "SX" => Ok(Self::SintMaarten),
            "SK" => Ok(Self::Slovakia),
            "SI" => Ok(Self::Slovenia),
            "SB" => Ok(Self::SolomonIslands),
            "SO" => Ok(Self::Somalia),
            "ZA" => Ok(Self::SouthAfrica),
            "GS" => Ok(Self::SouthGeorgiaAndSouthSandwichIslands),
            "SS" => Ok(Self::SouthSudan),
            "ES" => Ok(Self::Spain),
            "LK" => Ok(Self::SriLanka),
            "SD" => Ok(Self::Sudan),
            "SR" => Ok(Self::Suriname),
            "SJ" => Ok(Self::SvalbardAndJanMayen),
            "SE" => Ok(Self::Sweden),
            "CH" => Ok(Self::Switzerland),
            "SY" => Ok(Self::Syria),
            "TW" => Ok(Self::Taiwan),
            "TJ" => Ok(Self::Tajikistan),
            "TZ" => Ok(Self::Tanzania),
            "TH" => Ok(Self::Thailand),
            "TL" => Ok(Self::TimorLeste),
            "TG" => Ok(Self::Togo),
            "TK" => Ok(Self::Tokelau),
            "TO" => Ok(Self::Tonga),
            "TT" => Ok(Self::TrinidadAndTobago),
            "TN" => Ok(Self::Tunisia),
            "TR" => Ok(Self::Turkey),
            "TM" => Ok(Self::Turkmenistan),
            "TC" => Ok(Self::TurksAndCaicosIslands),
            "TV" => Ok(Self::Tuvalu),
            "UG" => Ok(Self::Uganda),
            "UA" => Ok(Self::Ukraine),
            "AE" => Ok(Self::UnitedArabEmirates),
            "GB" => Ok(Self::UnitedKingdom),
            "US" => Ok(Self::UnitedStates),
            "UM" => Ok(Self::UnitedStatesMinorOutlyingIslands),
            "UY" => Ok(Self::Uruguay),
            "UZ" => Ok(Self::Uzbekistan),
            "VU" => Ok(Self::Vanuatu),
            "VE" => Ok(Self::Venezuela),
            "VN" => Ok(Self::Vietnam),
            "VG" => Ok(Self::VirginIslandsBritish),
            "VI" => Ok(Self::VirginIslandsUs),
            "WF" => Ok(Self::WallisAndFutuna),
            "EH" => Ok(Self::WesternSahara),
            "YE" => Ok(Self::Yemen),
            "ZM" => Ok(Self::Zambia),
            "ZW" => Ok(Self::Zimbabwe),
            other => Err(UnknownCountryCode(other.to_owned())),
        }
    }
}

impl CloudFrontCountry {
    /// Returns the ISO 3166-1 alpha-2 code, matching what CloudFront sends.
    pub fn as_alpha2(&self) -> &'static str {
        match self {
            Self::Afghanistan => "AF",
            Self::AlandIslands => "AX",
            Self::Albania => "AL",
            Self::Algeria => "DZ",
            Self::AmericanSamoa => "AS",
            Self::Andorra => "AD",
            Self::Angola => "AO",
            Self::Anguilla => "AI",
            Self::Antarctica => "AQ",
            Self::AntiguaAndBarbuda => "AG",
            Self::Argentina => "AR",
            Self::Armenia => "AM",
            Self::Aruba => "AW",
            Self::Australia => "AU",
            Self::Austria => "AT",
            Self::Azerbaijan => "AZ",
            Self::Bahamas => "BS",
            Self::Bahrain => "BH",
            Self::Bangladesh => "BD",
            Self::Barbados => "BB",
            Self::Belarus => "BY",
            Self::Belgium => "BE",
            Self::Belize => "BZ",
            Self::Benin => "BJ",
            Self::Bermuda => "BM",
            Self::Bhutan => "BT",
            Self::Bolivia => "BO",
            Self::BonaireSintEustatiusAndSaba => "BQ",
            Self::BosniaAndHerzegovina => "BA",
            Self::Botswana => "BW",
            Self::BouvetIsland => "BV",
            Self::Brazil => "BR",
            Self::BritishIndianOceanTerritory => "IO",
            Self::Brunei => "BN",
            Self::Bulgaria => "BG",
            Self::BurkinaFaso => "BF",
            Self::Burundi => "BI",
            Self::CaboVerde => "CV",
            Self::Cambodia => "KH",
            Self::Cameroon => "CM",
            Self::Canada => "CA",
            Self::CaymanIslands => "KY",
            Self::CentralAfricanRepublic => "CF",
            Self::Chad => "TD",
            Self::Chile => "CL",
            Self::China => "CN",
            Self::ChristmasIsland => "CX",
            Self::CocosIslands => "CC",
            Self::Colombia => "CO",
            Self::Comoros => "KM",
            Self::Congo => "CG",
            Self::CongoDemocraticRepublic => "CD",
            Self::CookIslands => "CK",
            Self::CostaRica => "CR",
            Self::CoteDivoire => "CI",
            Self::Croatia => "HR",
            Self::Cuba => "CU",
            Self::Curacao => "CW",
            Self::Cyprus => "CY",
            Self::CzechRepublic => "CZ",
            Self::Denmark => "DK",
            Self::Djibouti => "DJ",
            Self::Dominica => "DM",
            Self::DominicanRepublic => "DO",
            Self::Ecuador => "EC",
            Self::Egypt => "EG",
            Self::ElSalvador => "SV",
            Self::EquatorialGuinea => "GQ",
            Self::Eritrea => "ER",
            Self::Estonia => "EE",
            Self::Eswatini => "SZ",
            Self::Ethiopia => "ET",
            Self::FalklandIslands => "FK",
            Self::FaroeIslands => "FO",
            Self::Fiji => "FJ",
            Self::Finland => "FI",
            Self::France => "FR",
            Self::FrenchGuiana => "GF",
            Self::FrenchPolynesia => "PF",
            Self::FrenchSouthernTerritories => "TF",
            Self::Gabon => "GA",
            Self::Gambia => "GM",
            Self::Georgia => "GE",
            Self::Germany => "DE",
            Self::Ghana => "GH",
            Self::Gibraltar => "GI",
            Self::Greece => "GR",
            Self::Greenland => "GL",
            Self::Grenada => "GD",
            Self::Guadeloupe => "GP",
            Self::Guam => "GU",
            Self::Guatemala => "GT",
            Self::Guernsey => "GG",
            Self::Guinea => "GN",
            Self::GuineaBissau => "GW",
            Self::Guyana => "GY",
            Self::Haiti => "HT",
            Self::HeardIslandAndMcdonaldIslands => "HM",
            Self::HolySee => "VA",
            Self::Honduras => "HN",
            Self::HongKong => "HK",
            Self::Hungary => "HU",
            Self::Iceland => "IS",
            Self::India => "IN",
            Self::Indonesia => "ID",
            Self::Iran => "IR",
            Self::Iraq => "IQ",
            Self::Ireland => "IE",
            Self::IsleOfMan => "IM",
            Self::Israel => "IL",
            Self::Italy => "IT",
            Self::Jamaica => "JM",
            Self::Japan => "JP",
            Self::Jersey => "JE",
            Self::Jordan => "JO",
            Self::Kazakhstan => "KZ",
            Self::Kenya => "KE",
            Self::Kiribati => "KI",
            Self::NorthKorea => "KP",
            Self::SouthKorea => "KR",
            Self::Kuwait => "KW",
            Self::Kyrgyzstan => "KG",
            Self::Laos => "LA",
            Self::Latvia => "LV",
            Self::Lebanon => "LB",
            Self::Lesotho => "LS",
            Self::Liberia => "LR",
            Self::Libya => "LY",
            Self::Liechtenstein => "LI",
            Self::Lithuania => "LT",
            Self::Luxembourg => "LU",
            Self::Macao => "MO",
            Self::Madagascar => "MG",
            Self::Malawi => "MW",
            Self::Malaysia => "MY",
            Self::Maldives => "MV",
            Self::Mali => "ML",
            Self::Malta => "MT",
            Self::MarshallIslands => "MH",
            Self::Martinique => "MQ",
            Self::Mauritania => "MR",
            Self::Mauritius => "MU",
            Self::Mayotte => "YT",
            Self::Mexico => "MX",
            Self::Micronesia => "FM",
            Self::Moldova => "MD",
            Self::Monaco => "MC",
            Self::Mongolia => "MN",
            Self::Montenegro => "ME",
            Self::Montserrat => "MS",
            Self::Morocco => "MA",
            Self::Mozambique => "MZ",
            Self::Myanmar => "MM",
            Self::Namibia => "NA",
            Self::Nauru => "NR",
            Self::Nepal => "NP",
            Self::Netherlands => "NL",
            Self::NewCaledonia => "NC",
            Self::NewZealand => "NZ",
            Self::Nicaragua => "NI",
            Self::Niger => "NE",
            Self::Nigeria => "NG",
            Self::Niue => "NU",
            Self::NorfolkIsland => "NF",
            Self::NorthMacedonia => "MK",
            Self::NorthernMarianaIslands => "MP",
            Self::Norway => "NO",
            Self::Oman => "OM",
            Self::Pakistan => "PK",
            Self::Palau => "PW",
            Self::Palestine => "PS",
            Self::Panama => "PA",
            Self::PapuaNewGuinea => "PG",
            Self::Paraguay => "PY",
            Self::Peru => "PE",
            Self::Philippines => "PH",
            Self::Pitcairn => "PN",
            Self::Poland => "PL",
            Self::Portugal => "PT",
            Self::PuertoRico => "PR",
            Self::Qatar => "QA",
            Self::Reunion => "RE",
            Self::Romania => "RO",
            Self::Russia => "RU",
            Self::Rwanda => "RW",
            Self::SaintBarthelemy => "BL",
            Self::SaintHelena => "SH",
            Self::SaintKittsAndNevis => "KN",
            Self::SaintLucia => "LC",
            Self::SaintMartin => "MF",
            Self::SaintPierreAndMiquelon => "PM",
            Self::SaintVincentAndTheGrenadines => "VC",
            Self::Samoa => "WS",
            Self::SanMarino => "SM",
            Self::SaoTomeAndPrincipe => "ST",
            Self::SaudiArabia => "SA",
            Self::Senegal => "SN",
            Self::Serbia => "RS",
            Self::Seychelles => "SC",
            Self::SierraLeone => "SL",
            Self::Singapore => "SG",
            Self::SintMaarten => "SX",
            Self::Slovakia => "SK",
            Self::Slovenia => "SI",
            Self::SolomonIslands => "SB",
            Self::Somalia => "SO",
            Self::SouthAfrica => "ZA",
            Self::SouthGeorgiaAndSouthSandwichIslands => "GS",
            Self::SouthSudan => "SS",
            Self::Spain => "ES",
            Self::SriLanka => "LK",
            Self::Sudan => "SD",
            Self::Suriname => "SR",
            Self::SvalbardAndJanMayen => "SJ",
            Self::Sweden => "SE",
            Self::Switzerland => "CH",
            Self::Syria => "SY",
            Self::Taiwan => "TW",
            Self::Tajikistan => "TJ",
            Self::Tanzania => "TZ",
            Self::Thailand => "TH",
            Self::TimorLeste => "TL",
            Self::Togo => "TG",
            Self::Tokelau => "TK",
            Self::Tonga => "TO",
            Self::TrinidadAndTobago => "TT",
            Self::Tunisia => "TN",
            Self::Turkey => "TR",
            Self::Turkmenistan => "TM",
            Self::TurksAndCaicosIslands => "TC",
            Self::Tuvalu => "TV",
            Self::Uganda => "UG",
            Self::Ukraine => "UA",
            Self::UnitedArabEmirates => "AE",
            Self::UnitedKingdom => "GB",
            Self::UnitedStates => "US",
            Self::UnitedStatesMinorOutlyingIslands => "UM",
            Self::Uruguay => "UY",
            Self::Uzbekistan => "UZ",
            Self::Vanuatu => "VU",
            Self::Venezuela => "VE",
            Self::Vietnam => "VN",
            Self::VirginIslandsBritish => "VG",
            Self::VirginIslandsUs => "VI",
            Self::WallisAndFutuna => "WF",
            Self::WesternSahara => "EH",
            Self::Yemen => "YE",
            Self::Zambia => "ZM",
            Self::Zimbabwe => "ZW",
        }
    }

    /// Returns the full English country name.
    pub fn as_name(&self) -> &'static str {
        match self {
            Self::Afghanistan => "Afghanistan",
            Self::AlandIslands => "Åland Islands",
            Self::Albania => "Albania",
            Self::Algeria => "Algeria",
            Self::AmericanSamoa => "American Samoa",
            Self::Andorra => "Andorra",
            Self::Angola => "Angola",
            Self::Anguilla => "Anguilla",
            Self::Antarctica => "Antarctica",
            Self::AntiguaAndBarbuda => "Antigua and Barbuda",
            Self::Argentina => "Argentina",
            Self::Armenia => "Armenia",
            Self::Aruba => "Aruba",
            Self::Australia => "Australia",
            Self::Austria => "Austria",
            Self::Azerbaijan => "Azerbaijan",
            Self::Bahamas => "Bahamas",
            Self::Bahrain => "Bahrain",
            Self::Bangladesh => "Bangladesh",
            Self::Barbados => "Barbados",
            Self::Belarus => "Belarus",
            Self::Belgium => "Belgium",
            Self::Belize => "Belize",
            Self::Benin => "Benin",
            Self::Bermuda => "Bermuda",
            Self::Bhutan => "Bhutan",
            Self::Bolivia => "Bolivia",
            Self::BonaireSintEustatiusAndSaba => "Bonaire Sint Eustatius and Saba",
            Self::BosniaAndHerzegovina => "Bosnia and Herzegovina",
            Self::Botswana => "Botswana",
            Self::BouvetIsland => "Bouvet Island",
            Self::Brazil => "Brazil",
            Self::BritishIndianOceanTerritory => "British Indian Ocean Territory",
            Self::Brunei => "Brunei",
            Self::Bulgaria => "Bulgaria",
            Self::BurkinaFaso => "Burkina Faso",
            Self::Burundi => "Burundi",
            Self::CaboVerde => "Cabo Verde",
            Self::Cambodia => "Cambodia",
            Self::Cameroon => "Cameroon",
            Self::Canada => "Canada",
            Self::CaymanIslands => "Cayman Islands",
            Self::CentralAfricanRepublic => "Central African Republic",
            Self::Chad => "Chad",
            Self::Chile => "Chile",
            Self::China => "China",
            Self::ChristmasIsland => "Christmas Island",
            Self::CocosIslands => "Cocos Islands",
            Self::Colombia => "Colombia",
            Self::Comoros => "Comoros",
            Self::Congo => "Congo",
            Self::CongoDemocraticRepublic => "Congo Democratic Republic",
            Self::CookIslands => "Cook Islands",
            Self::CostaRica => "Costa Rica",
            Self::CoteDivoire => "Cote d'Ivoire",
            Self::Croatia => "Croatia",
            Self::Cuba => "Cuba",
            Self::Curacao => "Curacao",
            Self::Cyprus => "Cyprus",
            Self::CzechRepublic => "Czech Republic",
            Self::Denmark => "Denmark",
            Self::Djibouti => "Djibouti",
            Self::Dominica => "Dominica",
            Self::DominicanRepublic => "Dominican Republic",
            Self::Ecuador => "Ecuador",
            Self::Egypt => "Egypt",
            Self::ElSalvador => "El Salvador",
            Self::EquatorialGuinea => "Equatorial Guinea",
            Self::Eritrea => "Eritrea",
            Self::Estonia => "Estonia",
            Self::Eswatini => "Eswatini",
            Self::Ethiopia => "Ethiopia",
            Self::FalklandIslands => "Falkland Islands",
            Self::FaroeIslands => "Faroe Islands",
            Self::Fiji => "Fiji",
            Self::Finland => "Finland",
            Self::France => "France",
            Self::FrenchGuiana => "French Guiana",
            Self::FrenchPolynesia => "French Polynesia",
            Self::FrenchSouthernTerritories => "French Southern Territories",
            Self::Gabon => "Gabon",
            Self::Gambia => "Gambia",
            Self::Georgia => "Georgia",
            Self::Germany => "Germany",
            Self::Ghana => "Ghana",
            Self::Gibraltar => "Gibraltar",
            Self::Greece => "Greece",
            Self::Greenland => "Greenland",
            Self::Grenada => "Grenada",
            Self::Guadeloupe => "Guadeloupe",
            Self::Guam => "Guam",
            Self::Guatemala => "Guatemala",
            Self::Guernsey => "Guernsey",
            Self::Guinea => "Guinea",
            Self::GuineaBissau => "Guinea-Bissau",
            Self::Guyana => "Guyana",
            Self::Haiti => "Haiti",
            Self::HeardIslandAndMcdonaldIslands => "Heard Island and McDonald Islands",
            Self::HolySee => "Holy See",
            Self::Honduras => "Honduras",
            Self::HongKong => "Hong Kong",
            Self::Hungary => "Hungary",
            Self::Iceland => "Iceland",
            Self::India => "India",
            Self::Indonesia => "Indonesia",
            Self::Iran => "Iran",
            Self::Iraq => "Iraq",
            Self::Ireland => "Ireland",
            Self::IsleOfMan => "Isle of Man",
            Self::Israel => "Israel",
            Self::Italy => "Italy",
            Self::Jamaica => "Jamaica",
            Self::Japan => "Japan",
            Self::Jersey => "Jersey",
            Self::Jordan => "Jordan",
            Self::Kazakhstan => "Kazakhstan",
            Self::Kenya => "Kenya",
            Self::Kiribati => "Kiribati",
            Self::NorthKorea => "North Korea",
            Self::SouthKorea => "South Korea",
            Self::Kuwait => "Kuwait",
            Self::Kyrgyzstan => "Kyrgyzstan",
            Self::Laos => "Laos",
            Self::Latvia => "Latvia",
            Self::Lebanon => "Lebanon",
            Self::Lesotho => "Lesotho",
            Self::Liberia => "Liberia",
            Self::Libya => "Libya",
            Self::Liechtenstein => "Liechtenstein",
            Self::Lithuania => "Lithuania",
            Self::Luxembourg => "Luxembourg",
            Self::Macao => "Macao",
            Self::Madagascar => "Madagascar",
            Self::Malawi => "Malawi",
            Self::Malaysia => "Malaysia",
            Self::Maldives => "Maldives",
            Self::Mali => "Mali",
            Self::Malta => "Malta",
            Self::MarshallIslands => "Marshall Islands",
            Self::Martinique => "Martinique",
            Self::Mauritania => "Mauritania",
            Self::Mauritius => "Mauritius",
            Self::Mayotte => "Mayotte",
            Self::Mexico => "Mexico",
            Self::Micronesia => "Micronesia",
            Self::Moldova => "Moldova",
            Self::Monaco => "Monaco",
            Self::Mongolia => "Mongolia",
            Self::Montenegro => "Montenegro",
            Self::Montserrat => "Montserrat",
            Self::Morocco => "Morocco",
            Self::Mozambique => "Mozambique",
            Self::Myanmar => "Myanmar",
            Self::Namibia => "Namibia",
            Self::Nauru => "Nauru",
            Self::Nepal => "Nepal",
            Self::Netherlands => "Netherlands",
            Self::NewCaledonia => "New Caledonia",
            Self::NewZealand => "New Zealand",
            Self::Nicaragua => "Nicaragua",
            Self::Niger => "Niger",
            Self::Nigeria => "Nigeria",
            Self::Niue => "Niue",
            Self::NorfolkIsland => "Norfolk Island",
            Self::NorthMacedonia => "North Macedonia",
            Self::NorthernMarianaIslands => "Northern Mariana Islands",
            Self::Norway => "Norway",
            Self::Oman => "Oman",
            Self::Pakistan => "Pakistan",
            Self::Palau => "Palau",
            Self::Palestine => "Palestine",
            Self::Panama => "Panama",
            Self::PapuaNewGuinea => "Papua New Guinea",
            Self::Paraguay => "Paraguay",
            Self::Peru => "Peru",
            Self::Philippines => "Philippines",
            Self::Pitcairn => "Pitcairn",
            Self::Poland => "Poland",
            Self::Portugal => "Portugal",
            Self::PuertoRico => "Puerto Rico",
            Self::Qatar => "Qatar",
            Self::Reunion => "Reunion",
            Self::Romania => "Romania",
            Self::Russia => "Russia",
            Self::Rwanda => "Rwanda",
            Self::SaintBarthelemy => "Saint Barthelemy",
            Self::SaintHelena => "Saint Helena",
            Self::SaintKittsAndNevis => "Saint Kitts and Nevis",
            Self::SaintLucia => "Saint Lucia",
            Self::SaintMartin => "Saint Martin",
            Self::SaintPierreAndMiquelon => "Saint Pierre and Miquelon",
            Self::SaintVincentAndTheGrenadines => "Saint Vincent and the Grenadines",
            Self::Samoa => "Samoa",
            Self::SanMarino => "San Marino",
            Self::SaoTomeAndPrincipe => "Sao Tome and Principe",
            Self::SaudiArabia => "Saudi Arabia",
            Self::Senegal => "Senegal",
            Self::Serbia => "Serbia",
            Self::Seychelles => "Seychelles",
            Self::SierraLeone => "Sierra Leone",
            Self::Singapore => "Singapore",
            Self::SintMaarten => "Sint Maarten",
            Self::Slovakia => "Slovakia",
            Self::Slovenia => "Slovenia",
            Self::SolomonIslands => "Solomon Islands",
            Self::Somalia => "Somalia",
            Self::SouthAfrica => "South Africa",
            Self::SouthGeorgiaAndSouthSandwichIslands => "South Georgia and South Sandwich Islands",
            Self::SouthSudan => "South Sudan",
            Self::Spain => "Spain",
            Self::SriLanka => "Sri Lanka",
            Self::Sudan => "Sudan",
            Self::Suriname => "Suriname",
            Self::SvalbardAndJanMayen => "Svalbard and Jan Mayen",
            Self::Sweden => "Sweden",
            Self::Switzerland => "Switzerland",
            Self::Syria => "Syria",
            Self::Taiwan => "Taiwan",
            Self::Tajikistan => "Tajikistan",
            Self::Tanzania => "Tanzania",
            Self::Thailand => "Thailand",
            Self::TimorLeste => "Timor-Leste",
            Self::Togo => "Togo",
            Self::Tokelau => "Tokelau",
            Self::Tonga => "Tonga",
            Self::TrinidadAndTobago => "Trinidad and Tobago",
            Self::Tunisia => "Tunisia",
            Self::Turkey => "Turkey",
            Self::Turkmenistan => "Turkmenistan",
            Self::TurksAndCaicosIslands => "Turks and Caicos Islands",
            Self::Tuvalu => "Tuvalu",
            Self::Uganda => "Uganda",
            Self::Ukraine => "Ukraine",
            Self::UnitedArabEmirates => "United Arab Emirates",
            Self::UnitedKingdom => "United Kingdom",
            Self::UnitedStates => "United States",
            Self::UnitedStatesMinorOutlyingIslands => "United States Minor Outlying Islands",
            Self::Uruguay => "Uruguay",
            Self::Uzbekistan => "Uzbekistan",
            Self::Vanuatu => "Vanuatu",
            Self::Venezuela => "Venezuela",
            Self::Vietnam => "Vietnam",
            Self::VirginIslandsBritish => "Virgin Islands British",
            Self::VirginIslandsUs => "Virgin Islands US",
            Self::WallisAndFutuna => "Wallis and Futuna",
            Self::WesternSahara => "Western Sahara",
            Self::Yemen => "Yemen",
            Self::Zambia => "Zambia",
            Self::Zimbabwe => "Zimbabwe",
        }
    }
}

/// `Display` renders the full English country name.
impl std::fmt::Display for CloudFrontCountry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_name())
    }
}

/// Returned by `FromStr` when the two-letter code is not recognised.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnknownCountryCode(pub String);

impl std::fmt::Display for UnknownCountryCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unknown CloudFront country code: {:?}", self.0)
    }
}

impl std::error::Error for UnknownCountryCode {}

pub trait HasCloudfrontViewerCountry {
    fn get_cloudfront_viewer_country(&self) -> Option<CloudFrontCountry>;
}

impl HasCloudfrontViewerCountry for axum::http::HeaderMap {
    fn get_cloudfront_viewer_country(&self) -> Option<CloudFrontCountry> {
        self.get("cloudfront-viewer-country")
            .and_then(|x| x.to_str().ok())
            .and_then(|x| CloudFrontCountry::from_str(x).ok())
    }
}
